# 集成模型配置文件

# 输出目录（用于保存模型和评估结果）
output_dir: "output/ensemble"

# 样本数据目录
benign_dir: "data/benign"
malware_dir: "data/malware"

# 样本限制（每类样本的最大数量，用于调试）
# 设置为null将使用所有样本
sample_limit: null

# 数据划分
test_size: 0.2
random_state: 42

# 特征工程
top_features: 500  # 选择的特征数量

# LightGBM模型参数
lgb_params:
  objective: "binary"
  metric: "auc"
  boosting_type: "gbdt"
  learning_rate: 0.05
  num_leaves: 64
  max_depth: 6
  min_data_in_leaf: 10
  bagging_fraction: 0.8
  bagging_freq: 5
  feature_fraction: 0.8
  lambda_l1: 0.1
  lambda_l2: 0.1
  
n_estimators: 1000
early_stopping_rounds: 50

# 是否进行参数优化
optimize_params: false
n_trials: 100  # 参数优化的试验次数

# 深度学习模型参数
embedding_dim: 128
hidden_dim: 128
lstm_layers: 1
fc_hidden: 256
dropout: 0.3
learning_rate: 0.001
batch_size: 64
epochs: 30
swa_start: 5

# 模型集成权重 [深度学习模型权重, LightGBM模型权重]
ensemble_weights: [0.6, 0.4]

# 多模态特征设置
use_byte_sequence: true
use_image: true
byte_sequence_max_length: 2048
image_width: 32
image_max_bytes: 4096

# 并行处理
n_jobs: 4
num_workers: 4

# 可选：预先处理好的特征路径
# 如果提供，将直接加载而不是重新提取
features_path: null 